# Site settings
title: Hosjiu
email: hosjiu1702@gmail.com
description: "Tôi thích hiểu bản chất cốt lõi của mọi vấn đề.
Đó là lý do tôi viết blog này."
baseurl: ""
url: "http://hosjiu1702.github.io"
twitter_username: Hosjiu
github_username:  Hosjiu1702

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
