# Site settings
title:              "Seita's Place"
email:              seita@cs.berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  This is my blog, where I have written over 300 articles on a variety of
  topics. Recent posts tend to focus on computer science, my area of specialty
  as a Ph.D. student at UC Berkeley.
baseurl:            ""
url:                "https://danieltakeshi.github.io"
twitter_username:   (Never!)
github_username:    DanielTakeshi
future:             True
timezone:           America/Los_Angeles

# Build settings
markdown:           kramdown
gems:               [jekyll-paginate]
paginate:           15
